<?php
define('_VIEW3BOARD_',TRUE);
include_once "../view3.php";

$arr = array(
array("name"=>"천호","addr_road"=>"서울시 강동구 구천면로 192, 상가동 111호(천호역한강푸르지오시티)","tel"=>"02-473-9293","addr_y"=>"","addr_x"=>""),
array("name"=>"대구혁신도시","addr_road"=>"대구광역시 동구 이노밸리로 42길 10-4,101호(각산동)","tel"=>"053)964-8803","addr_y"=>"","addr_x"=>""),
array("name"=>"안성공도","addr_road"=>"경기 안성시 공도읍 공도로 91","tel"=>"031-618-4778","addr_y"=>"","addr_x"=>""),
array("name"=>"가양","addr_road"=>"서울특별시 강서구 양천로 401, a동 1층 110호(가양,강서한강자이타워)","tel"=>"02-6968-5993","addr_y"=>"","addr_x"=>""),
array("name"=>"신도림","addr_road"=>"서울시 구로구 경인로 661, 1층 127-1호(신도림동,신도림1차푸르지오)","tel"=>"02-2633-0744","addr_y"=>"","addr_x"=>""),
array("name"=>"춘천한림대","addr_road"=>"강원도 춘천시 교동 156","tel"=>"033-251-7011","addr_y"=>"","addr_x"=>""),
array("name"=>"상암 DMC","addr_road"=>"서울 마포구 상암동 1597","tel"=>"02-373-2235","addr_y"=>"","addr_x"=>""),
array("name"=>"울산구영","addr_road"=>"울산 울주군 범서읍 구영리 848-1","tel"=>" 052-243-1002","addr_y"=>"","addr_x"=>""),
array("name"=>"성신여대","addr_road"=>"서울시 성북구 동선동 1가 4-13 1층","tel"=>"02-953-0204","addr_y"=>"","addr_x"=>""),
array("name"=>"중화역","addr_road"=>"서울시 중랑구 중화동 303-54 한훈빌딩 1층","tel"=>"02-434-3466","addr_y"=>"","addr_x"=>""),
array("name"=>"인천캠퍼스타운","addr_road"=>"인천 연수구 송도과락로27번길 55,D동105호(롯데캐슬 캠퍼스타운)","tel"=>"031-815-0916","addr_y"=>"","addr_x"=>""),
array("name"=>"제주삼화","addr_road"=>"제주시 지석13길 2-2, 1층(삼양2동)","tel"=>"064-721-4150","addr_y"=>"","addr_x"=>""),
array("name"=>"충무로","addr_road"=>"서울시 중구 초동 41-6","tel"=>"02-2266-4913","addr_y"=>"","addr_x"=>""),
array("name"=>"거제고현","addr_road"=>"경상남도 거제시 고현동 978-10 109호","tel"=>"055-637-3121","addr_y"=>"","addr_x"=>""),
array("name"=>"대전탄방","addr_road"=>"대전시 서구 탄방동 792번지","tel"=>"042-472-7878","addr_y"=>"","addr_x"=>""),
array("name"=>"의정부신곡","addr_road"=>"경기 의정부시 발곡로 24. 지상1층 103호(신곡동)","tel"=>"031-877-5510","addr_y"=>"","addr_x"=>""),
array("name"=>"양산물금","addr_road"=>"경남 양산시 물금읍 화합2길 4-1,1층","tel"=>"055-381-0111","addr_y"=>"","addr_x"=>""),
array("name"=>"명지오션시티","addr_road"=>"부산시 강서구 명지오션시티4로82, 105호(명지동,리치언드프라자)","tel"=>"051-202-8804","addr_y"=>"","addr_x"=>""),
array("name"=>"거제아주","addr_road"=>"경남 거제시 아주1로 70, 1층(아주동)","tel"=>"055-681-7723","addr_y"=>"","addr_x"=>""),
array("name"=>"신대방역","addr_road"=>"서울시 관악구 신림동 517-57","tel"=>"02-852-1102","addr_y"=>"","addr_x"=>""),
array("name"=>"양산증산역","addr_road"=>" 양산시 물금읍 증산역로 153, 정우프라자 1층 104호","tel"=>"055-367-2715","addr_y"=>"","addr_x"=>""),
array("name"=>"울산언양","addr_road"=>"울산 울주군 삼남면 교동리 1567-13","tel"=>"052-254-0224","addr_y"=>"","addr_x"=>""),
array("name"=>"아산용화","addr_road"=>"충남 아산시 용화동 1240","tel"=>"041-532-1202","addr_y"=>"","addr_x"=>""),
array("name"=>"문정테라타워","addr_road"=>"서울시 송파구 문정동 651 테라타워1층","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"부산 명륜","addr_road"=>"부산광역시 동래구 명륜동 782번지 127층 비 108호","tel"=>"051-558-7696","addr_y"=>"","addr_x"=>""),
array("name"=>"광혜원","addr_road"=>"충북 진천군 광혜원면 구암길 638-22","tel"=>"043-532-2632","addr_y"=>"","addr_x"=>""),
array("name"=>"거제옥포","addr_road"=>"경남 거제 옥포동 874-2","tel"=>"055-687-7757","addr_y"=>"","addr_x"=>""),
array("name"=>"구파발","addr_road"=>"서울시 은평구 진관동 87-13","tel"=>"02-386-9898","addr_y"=>"","addr_x"=>""),
array("name"=>"남원","addr_road"=>"전북 남원시 하정동 128-1","tel"=>"063-632-9858","addr_y"=>"","addr_x"=>""),
array("name"=>"정관신도시","addr_road"=>"부산시 기장군 모전리 730번지 이지더원3차 상가322동 114호","tel"=>"051-727-7151","addr_y"=>"","addr_x"=>""),
array("name"=>"영주택지","addr_road"=>"경북 영주시 가흥동 1548-1","tel"=>"054-632-7058","addr_y"=>"","addr_x"=>""),
array("name"=>"학동","addr_road"=>"서울시 강남구 논현동 211-12","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"논현","addr_road"=>"서울시 강남구 강남대로 524, 101호","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"마곡","addr_road"=>"서울시 강서구 마곡동 773-2번지 124호","tel"=>"02-2658-7268","addr_y"=>"","addr_x"=>""),
array("name"=>"광주하남","addr_road"=>"광주광역시 광산구 용아로379번길 8, 1층","tel"=>"062-952-3390","addr_y"=>"","addr_x"=>""),
array("name"=>"발산","addr_road"=>"서울시 강서구 마곡동 794-1번지 116호","tel"=>"02-2658-0885","addr_y"=>"","addr_x"=>""),
array("name"=>"대전을지","addr_road"=>"대전시 서구 둔산2동 1352번지","tel"=>"042-488-2517","addr_y"=>"","addr_x"=>""),
array("name"=>"건대 로데오","addr_road"=>"서울시 광진구 자양동 9-31번지","tel"=>" 02-466-1969","addr_y"=>"","addr_x"=>""),
array("name"=>"남양주 호평","addr_road"=>"경기 남양주시 호평동 642-2 123호","tel"=>"031-591-8765","addr_y"=>"","addr_x"=>""),
array("name"=>"화천 터미널","addr_road"=>"강원도 화천군 화천읍 상승로 42-5","tel"=>"033 442 1942","addr_y"=>"","addr_x"=>""),
array("name"=>"마곡나루","addr_road"=>"서울 강서구 마곡중앙로 161-11 A동 128호","tel"=>"02-3663-1969","addr_y"=>"","addr_x"=>""),
array("name"=>"인천서창2지구","addr_road"=>"인천광역시 남동구 서창남순환로 223 아페리온A-125","tel"=>"070-8623-4560","addr_y"=>"","addr_x"=>""),
array("name"=>"울진","addr_road"=>"경북 울진군 울진읍 읍내3길 23","tel"=>"054-783-9994","addr_y"=>"","addr_x"=>""),
array("name"=>"용산","addr_road"=>"서울 용산구 한강로2가 342 B244호","tel"=>"02-792-7474","addr_y"=>"","addr_x"=>""),
array("name"=>"대구도원","addr_road"=>"대구광역시 달서구 한실로 93, 1층","tel"=>"053-634-1249","addr_y"=>"","addr_x"=>""),
array("name"=>"천안법원","addr_road"=>"충남 천안시 동남구 청당동 488번지","tel"=>"041-557-1202","addr_y"=>"","addr_x"=>""),
array("name"=>"원광대","addr_road"=>"전북 익산시 신용동 55-1","tel"=>"063-858-0508","addr_y"=>"","addr_x"=>""),
array("name"=>"안양호계","addr_road"=>"경기 안양시 동안구 호계동 985-5","tel"=>"031-458-7789","addr_y"=>"","addr_x"=>""),
array("name"=>"방화역","addr_road"=>"서울시 강서구 방화대로47가길 7, 112호","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"부천상동","addr_road"=>"경기 부천시 원미구 상동 541-1 109호","tel"=>"032-326-2993","addr_y"=>"","addr_x"=>""),
array("name"=>"분당야탑","addr_road"=>"경기 성남시 분당구 야탑동 367-4","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"수원정자","addr_road"=>"경기 수원시 장안구 정자동 44-58","tel"=>"031-298-9490","addr_y"=>"","addr_x"=>""),
array("name"=>"부산동서대","addr_road"=>"부산광역시 사상구 주례동 166-24번지","tel"=>"051-311-5644","addr_y"=>"","addr_x"=>""),
array("name"=>"평택이충","addr_road"=>"경기 평택시 이충동 668-2 보람플러스2 , 102호","tel"=>"031-666-4977","addr_y"=>"","addr_x"=>""),
array("name"=>"단대오거리","addr_road"=>"경기 성남시 중앙동 광명로 262번지","tel"=>"031-734-9617","addr_y"=>"","addr_x"=>""),
array("name"=>"센텀시티","addr_road"=>"부산광역시 해운대구 재송동 1208-2, B동 111호","tel"=>"070-5172-1306","addr_y"=>"","addr_x"=>""),
array("name"=>"대구대실역","addr_road"=>"대구광역시 달성군 대실역남로 10","tel"=>"053-585-3456","addr_y"=>"","addr_x"=>""),
array("name"=>"남성역","addr_road"=>"서울시 동작구 사당동 252-17 (서림빌딩)","tel"=>"02-3476-7776","addr_y"=>"","addr_x"=>""),
array("name"=>"김포장기","addr_road"=>"경기 김포시 장기동 1622 동서메디칼빌딩 103호","tel"=>"031-984-3556","addr_y"=>"","addr_x"=>""),
array("name"=>"해운대장산","addr_road"=>"부산광역시 해운대구 좌동 1460-2, 101동 101호","tel"=>"051-704-2570","addr_y"=>"","addr_x"=>""),
array("name"=>"서면","addr_road"=>"부산광역시 진구 부전동 198-7","tel"=>"051-808-9458","addr_y"=>"","addr_x"=>""),
array("name"=>"길동","addr_road"=>"서울시 강동구 길동 406-11, 301호","tel"=>"02-6487-7275","addr_y"=>"","addr_x"=>""),
array("name"=>"창원봉곡","addr_road"=>"경남 창원시 봉곡동 33-9","tel"=>"055-602-6885","addr_y"=>"","addr_x"=>""),
array("name"=>"원주무실","addr_road"=>"강원 원주시 무실동 1855-1 102호","tel"=>"033-734-3914","addr_y"=>"","addr_x"=>""),
array("name"=>"조치원역","addr_road"=>"세종시 조치원읍 으뜸길 260, 101호","tel"=>"044-867-8529","addr_y"=>"","addr_x"=>""),
array("name"=>"양천향교","addr_road"=>"서울시 강서구 마곡동 776-3,122-2","tel"=>"02-6052-5215","addr_y"=>"","addr_x"=>""),
array("name"=>"창원상남","addr_road"=>"경남 창원시 성산구 상남동1-3,롯데빌딩1층 105호일부","tel"=>"055-274-2788","addr_y"=>"","addr_x"=>""),
array("name"=>"남원도통","addr_road"=>"전북 남원시 용성로217","tel"=>"063-635-9082","addr_y"=>"","addr_x"=>""),
array("name"=>"협성대","addr_road"=>"경기 화성시 봉담읍 삼리 11-14","tel"=>"031-293-2227","addr_y"=>"","addr_x"=>""),
array("name"=>"시흥배곧","addr_road"=>"경기 시흥시 정왕동 1771-1 NCT배움터 106호","tel"=>"031-433-9997","addr_y"=>"","addr_x"=>""),
array("name"=>"진해석동","addr_road"=>"경남 창원시 진해구 석동 142-9","tel"=>"055-545-5933","addr_y"=>"","addr_x"=>""),
array("name"=>"광교상현역","addr_road"=>"경기 용인시 수지구 상현동 117-7번지 드림타워 102호","tel"=>"-","addr_y"=>"","addr_x"=>""),
array("name"=>"제주화북","addr_road"=>"제주시 일주동로 183번지","tel"=>"064-751-4150","addr_y"=>"","addr_x"=>""),
array("name"=>"연산파크시티","addr_road"=>"부산광역시 연제구 안연로33 더샵파크시티상가 E동 107호","tel"=>"051-867-4729","addr_y"=>"","addr_x"=>""),
array("name"=>"방이사거리","addr_road"=>"서울시 송파구 송파동 오금로 18길 5","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"아시아드선수촌","addr_road"=>"인천광역시 남동구 선수촌공원로23번길 1","tel"=>"032-464-5878","addr_y"=>"","addr_x"=>""),
array("name"=>"중계","addr_road"=>"서울시 노원구 중계본동 364-20 그린코아상가 103호","tel"=>"-","addr_y"=>"","addr_x"=>""),
array("name"=>"동국대","addr_road"=>"서울시 중구 필동3가 10-8(서애로22)","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"부산광안","addr_road"=>"부산광역시 수영구 광안동 496-23","tel"=>"070-8918-6854","addr_y"=>"","addr_x"=>""),
array("name"=>"인천갈산","addr_road"=>"인천광역시 부평구 평천로 300, 1층","tel"=>"032-566-6883","addr_y"=>"","addr_x"=>""),
array("name"=>"정다운사람들의료재단","addr_road"=>"경남 창원시 마산회원구 봉양로 160","tel"=>"055-295-7600","addr_y"=>"","addr_x"=>""),
array("name"=>"신길동","addr_road"=>"서울시 영등포구 신길동 2363번지","tel"=>"02-844-8666","addr_y"=>"","addr_x"=>""),
array("name"=>"광주문흥","addr_road"=>"광주광역시 북구 문흥동 995-1","tel"=>"062-447-1010","addr_y"=>"","addr_x"=>""),
array("name"=>"평택법원","addr_road"=>"경기 평택시 동삭동 662-5","tel"=>"031-651-6429","addr_y"=>"","addr_x"=>""),
array("name"=>"전주서곡세무서","addr_road"=>"전북 전주시 완산구 효자동3가 1419-1","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"용인기흥구청","addr_road"=>"경기 용인시 기흥구 구갈동 354-8 로얄프라자","tel"=>"031-286-5216","addr_y"=>"","addr_x"=>""),
array("name"=>"서면일번가","addr_road"=>"부산광역시 진구 부전동 232-32","tel"=>"051-805-1616","addr_y"=>"","addr_x"=>""),
array("name"=>"대구노원","addr_road"=>"대구광역시 북구 팔달로27길 81, 1층(노원동3가)","tel"=>"053-525-8227","addr_y"=>"","addr_x"=>""),
array("name"=>"안락","addr_road"=>"부산광역시 동래구 안락로 140","tel"=>"051-917-4242","addr_y"=>"","addr_x"=>""),
array("name"=>"청주지웰시티","addr_road"=>"충북 청주시 흥덕구 북대동 497-13, 101호","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"목표용해지구","addr_road"=>"전남 목포시 용해지구로85 백련메디컬프라자 108호","tel"=>"061-980-7806","addr_y"=>"","addr_x"=>""),
array("name"=>"대구반야월시장","addr_road"=>"대구광역시 동구 서호동 81-5","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"군산수송","addr_road"=>"전북 군산시 수송동 868","tel"=>"063-432-9977","addr_y"=>"","addr_x"=>""),
array("name"=>"제주연동","addr_road"=>"제주시 신대로20길 46","tel"=>"064-711-4929","addr_y"=>"","addr_x"=>""),
array("name"=>"광주전남대","addr_road"=>"광주광역시 북구 용봉동 161-50","tel"=>"062-444-0082","addr_y"=>"","addr_x"=>""),
array("name"=>"아산모종","addr_road"=>"충남 아산시 모종동 648번지 103호","tel"=>"041-542-8586","addr_y"=>"","addr_x"=>""),
array("name"=>"전주송천","addr_road"=>"전주시 덕진구 시천로 39  대명아파트 상가","tel"=>"063-254-3234","addr_y"=>"","addr_x"=>""),
array("name"=>"부산시청","addr_road"=>"부산광역시 연제구 연산동 1364-8","tel"=>"070-8860-9352","addr_y"=>"","addr_x"=>""),
array("name"=>"사직","addr_road"=>"부산광역시 동래구 사직동 93-6 자이언츠파크 122호","tel"=>"051-505-0515","addr_y"=>"","addr_x"=>""),
array("name"=>"제주한라병원","addr_road"=>"제주시 연동 1964-3","tel"=>"064-900-4945","addr_y"=>"","addr_x"=>""),
array("name"=>"이천부발","addr_road"=>"경기 이천시 부발읍 아미리 670-5 리슈빌상가 105호","tel"=>"031-637-0382","addr_y"=>"","addr_x"=>""),
array("name"=>"가평현리","addr_road"=>"경기 가평군 조종면 현리 409-1","tel"=>"031-585-8582","addr_y"=>"","addr_x"=>""),
array("name"=>"무안남악","addr_road"=>"전남 무안군 삼향읍 남악3로71 더트리폴리암 125호","tel"=>"061-281-1092","addr_y"=>"","addr_x"=>""),
array("name"=>"부평청천","addr_road"=>"인천광역시 부평구 청천동 236-20","tel"=>"032-516-7775","addr_y"=>"","addr_x"=>""),
array("name"=>"구미산동","addr_road"=>"경북 구미시 산동면 신당리 1446","tel"=>"070-7543-2225","addr_y"=>"","addr_x"=>""),
array("name"=>"동대문역사문화공원역","addr_road"=>"서울시 중구 을지로 282-1","tel"=>"02-2285-4354","addr_y"=>"","addr_x"=>""),
array("name"=>"암사역","addr_road"=>"서울시 강동구 암사동 512","tel"=>"02-428-1204","addr_y"=>"","addr_x"=>""),
array("name"=>"나주혁신","addr_road"=>"전남 나주시 상야2길16, 109호","tel"=>"061-334-1715","addr_y"=>"","addr_x"=>""),
array("name"=>"금천롯데캐슬파크","addr_road"=>"서울시 금천구 독산동 427-1 금천롯데캐슬골드파크3차 B113호","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"인천계양구청","addr_road"=>"인천광역시 계양구 계산동 1062 하이베라스B동 112호","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"천안신불당","addr_road"=>"충청남도 천안시 서북구 불당동 1543번지","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"천왕역","addr_road"=>"서울 구로구 오리로 1154, 1-3호","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"대구팔거역","addr_road"=>"대구광역시 북구 동천로23길 30-21, 1층 101호","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"평택도곡초점","addr_road"=>"경기도 평택시 포승읍 여술로 44번길 10","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"개봉역사","addr_road"=>"서울 구로구 경인로 40길 47 ㈜경우물산 3층","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"경기광주태전","addr_road"=>"경기도 광주시 태봉로 20","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"안동옥동","addr_road"=>"경상북도 안동시 경북대로 392","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"수영","addr_road"=>"부산광역시 수영구 광안동 50-2","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"구미봉곡","addr_road"=>"경상북도 구미시 봉곡로 172","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"광주조선대","addr_road"=>"광주광역시 동구 학동 520-4","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"금천시흥","addr_road"=>"서울특별시 금천구 시흥동 220-72","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"포항원동","addr_road"=>"경상북도 포항시 남구 오천읍 원리 893-56","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"김해외동","addr_road"=>"경상남도 김해시 외동 함박로 102, 110호","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"전주객사","addr_road"=>"전라북도 전주시 완산구 고사동 375-2","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"광주화정","addr_road"=>"광주광역시 서구 화정동 729-2","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"부산토곡","addr_road"=>"부산광역시 연제구 연산동 418-10","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"미아민병원","addr_road"=>"서울특별지 강북구 도봉로 155","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"전주아중","addr_road"=>"전라북도 전주시 덕진구 인후동 912-6","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"춘천강원대 후문","addr_road"=>"강원도 춘천시 효자동 628-10","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"경기광주 경안","addr_road"=>"경기도 광주시 중앙로 102","tel"=>"031-761-9988","addr_y"=>"","addr_x"=>""),
array("name"=>"동탄호수공원","addr_road"=>"경기도 화성시 동탄대로198 드림타워 108호","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"인천청라","addr_road"=>"인천시 서구 청라동 164-1 엑슬루타워 145호","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"순천연향","addr_road"=>"순천시 연향동 1340-2","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"인천신기","addr_road"=>"인천광역시 미추홀구 주안동 1464-31","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"파주금촌","addr_road"=>"경기도 파주시 금촌동 60-1","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"김포구래","addr_road"=>"김포시 구래동 6882-4번지 104호","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"인천만수","addr_road"=>"인천 남동구 만수동 72-29","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"의정부 신곡 백병원","addr_road"=>"경기도 의정부시 금신로 323 대영프리자 1층","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"인천연수","addr_road"=>"인천 연수 연수1동 522-7","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"홍제역","addr_road"=>"서울 서대문구 홍제동 172-8번지 2,3층","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"인천청사도화","addr_road"=>"인천광역시 미추홀구 도화동 122-73","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"전주KBS","addr_road"=>"전라북도 전주시 완산구 효자동3가 1633-4","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"영등포문래","addr_road"=>"서울 영등포구 문래동6가 8","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"포항양덕","addr_road"=>"경북 포항시 북구 양덕동 1463","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"문경모전","addr_road"=>"경북 문경시 모전동 1176","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"광주상무지구","addr_road"=>"광주광역시 서구 시청로27 151호","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"동대구시장","addr_road"=>"대구 북구 대현동 407-12","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"동탄호수공원우성","addr_road"=>"경기도 화성시 동탄순환대로127-17 106호","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"울산송정","addr_road"=>"울산 북구 박상진3로 73","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"김포풍무","addr_road"=>"경기도 김포시 풍무로146번길 18 궁강리체 102호","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"아산배방","addr_road"=>"충남 아산시 배방읍 공수리 1563","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"부산명장역","addr_road"=>"부산광역시 동래구 명장동 61-1","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"여수여서","addr_road"=>"전라남도 여수시 여문문화1길 13","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"춘천온의","addr_road"=>"춘천시 춘천로17번길 31","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"화성송산리","addr_road"=>"경기도 화성시 양감면 정문송산로 145","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"거제상문","addr_road"=>"거제시 거제중앙로 1537 102호","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"미사역","addr_road"=>"경기도 하남시 미사강변동로 85 137호","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"김포운양","addr_road"=>"경기도 김포시 김포한강1로 250 골든타임 124,125호","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"동탄북광장","addr_road"=>"경기도 화성시 동탄반석로 204 101호","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"광주수완","addr_road"=>"광주광역시 광산구 수완동 1412","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"부평구청","addr_road"=>"인천시 부평구 부평대로 153 129호","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"판교 우림 W 시티","addr_road"=>"성남시 분당구 판교로255번길 9-22 145호","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"인천당하","addr_road"=>"인천광역시 서구 당하동 909","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"대구대곡","addr_road"=>"대구시 달서구 대곡동 620번지","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"광주첨단","addr_road"=>"광주 광산구 쌍암동 694-58번지","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"부산진경찰서","addr_road"=>"부산광역시 부산진구 부전동 474-51","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"판교H스퀘어","addr_road"=>"경기 성남시 분당구 판교역로 231 H스퀘어 S동 1층 117호","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"부산충무대로","addr_road"=>"부산시 서구 충무대로 163-2","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"김제검산","addr_road"=>"전북 김제시 검산동 1058-6","tel"=>"","addr_y"=>"","addr_x"=>""),
array("name"=>"인천가정루원시티","addr_road"=>"인천 서구 가정동 609-1, 105호(호반센트럴)","tel"=>"","addr_y"=>"","addr_x"=>""),
);


?>
<script src="<?=$root?>/js/jquery-1.12.0.min.js"></script>
<script>
var addr_arr = <?php echo json_encode($arr)?>;
var geoLat,geoLng;
var cnt = 0;
var markGeocode = function(response) {
    if(response.channel.result > 0) {
        geoLat = response.channel.item[0].lat,
        geoLng = response.channel.item[0].lng;
        addr_arr[cnt]['addr_y'] = geoLat;
        addr_arr[cnt]['addr_x'] = geoLng;
        cnt++;
    }
};
jQuery(function($){
    var requestGeocode = function(address) {
        var requestUrl = 'http://view3.net/_outline/daum_api_migration/local/geo/addr2coord?q='+encodeURI(address)+'&output=json&callback=markGeocode';
     	var s = $('<script type="text/javascript" src="'+requestUrl+'">');
        $('body').append(s);
    };
    for (var i = 0; i < addr_arr.length; i++) {
        requestGeocode(addr_arr[i]['addr_road']);
    }
    console.log(addr_arr);
});
</script>
